behaviors:
  RunnerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3          # Aumentado ligeramente para más entropía (exploración)
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256     # Aumentado a 256 para mejor capacidad de abstracción (sensores 3D)
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 3000000      # Suficiente para ver convergencia
    time_horizon: 128       # Aumentado para que relacione acciones pasadas con rewards futuros
    summary_freq: 10000


  PoliceAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 5120
      learning_rate: 5.0e-4
      beta: 1.0e-3
      epsilon: 0.35
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    max_steps: 2000000
    time_horizon: 32
    summary_freq: 5000
    threaded: false

env_settings:
  env_path: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
